### ISSUE TITLE
Error npm run build

### ISSUE THREAD

**Issue by peterlavey** [joeldenning/single-spa-examples#45] opened 2017-11-27 15:39 UTC
Fails after installation in the build script, the log says:

```
./bin/build-code
"." it is not recognized as an internal or external command, program or batch file executable.
```

I'm with windows operating system.

**Comment by TheMcMurder** [comment] 2017-12-12 22:55
It looks like this is a duplicate of https://github.com/CanopyTax/single-spa-examples/issues/40 I'll take a look at this right now.

**Closed as completed by TheMcMurder** 2017-12-12 22:55 UTC
Labels: duplicate

**Comment by TheMcMurder** [comment] 2017-12-12 23:12
There are some changes we'll need to make to the build scripts to get these to work on Windows, because most versions of windows don't support bash scripts.

There are a few workaround options:
1. Depending on which version of Windows you are using you can install the linux subsystem on windows https://docs.microsoft.com/en-us/windows/wsl/install-win10 and use bash on windows.
2. Modify the build scripts to be windows friendly and submit a PR
3. Run the commands form the build script manually in a windows friendly way

Ultimately the core problem is we used bash to chain all the of the various builds together and windows doesn't support bash scripts out of the box.

**Comment by internettrans** [comment] 2017-12-13 00:41
@peterlavey apologies for the slowness in fixing -- could you try it now? I just pushed up a commit that removed all the bash stuff and makes it cross platform.
